kind: pipeline
type: kubernetes
name: default

# workspace:
#   path: /podtato-head

steps:
  - name: build-entry
    image: plugins/docker
    settings:
      repo: europe-west1-docker.pkg.dev/k8s-ci-cd-1/podtato-head/entry
      dockerfile: ./podtato-head/podtato-head-microservices/cmd/entry/Dockerfile
      context: ./podtato-head/podtato-head-microservices
      registry: europe-west1-docker.pkg.dev
      tags:
        - latest
        - "1.0"
