kind: pipeline
type: kubernetes
name: default

# steps:
#   - name: build-entry
#     image: plugins/docker
#     settings:
#       repo: europe-west1-docker.pkg.dev/k8s-ci-cd-1/podtato-head/entry
#       dockerfile: ./podtato-head/podtato-head-microservices/cmd/entry/Dockerfile
#       context: ./podtato-head/podtato-head-microservices
#       registry: europe-west1-docker.pkg.dev
#       tags:
#         - latest
#         - "1.0"

steps:
  - name: docker-build
    image: google/cloud-sdk
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      - sleep 5
      - docker ps
      - gcloud auth configure-docker europe-west1-docker.pkg.dev
      # - gcloud auth configure-docker
      - cd podtato-head
      - chmod +x ./podtato-head-microservices/build/build.sh
      - make push-microservices-images

services:
  - name: docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}
# #
