format_version: 3
pipelines:
  deploy_app:
    group: sample
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    display_order: 1
    environment_variables:
    materials:
      git:
        git: https://github.com/wluh1/k8s-ci-cd-conf.git
        shallow_clone: true
        auto_update: true
        branch: master
    stages:
      - deploy_app:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: success
          jobs:
            build_image:
              timeout: 0
              elastic_profile_id: demo-app
              tasks:
                - exec:
                    arguments:
                      - -c
                      - gcloud container clusters get-credentials k8s-ci-cd-1-gke --zone europe-west1-b
                      - cd podtato-head
                      - helm upgrade --install podtato-head ./ --namespace default
                    command: /bin/bash
                    run_if: passed
