kind: PodChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: argocd
  name: argocd-pod-failure-3
spec:
  selector:
    namespaces:
      - argocd
    labelSelectors:
      app.kubernetes.io/component: server
      app.kubernetes.io/instance: argocd
  mode: one
  action: pod-kill
  gracePeriod: 0