kind: PodChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: drone
  name: drone-pod-failure-2
spec:
  selector:
    namespaces:
      - drone
    labelSelectors:
      io.drone.repo.name: k8s-ci-cd
  mode: one
  action: pod-kill
  gracePeriod: 0