format_version: 3
pipelines:
  deploy_app:
    group: sample
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    display_order: 1
    environment_variables:
    materials:
      git:
        git: https://github.com/wluh1/k8s-ci-cd-conf.git
        shallow_clone: true
        auto_update: true
        branch: main
    stages:
      - deploy_app:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: success
          jobs:
            build_image:
              timeout: 0
              elastic_profile_id: demo-app
              tasks:
                - exec:
                    arguments:
                      - -c
                      - curl -fsSL "https://github.com/GoogleCloudPlatform/docker-credential-gcr/releases/download/v2.1.0/docker-credential-gcr_linux_amd64-2.1.0.tar.gz" | tar xz --to-stdout ./docker-credential-gcr > /usr/bin/docker-credential-gcr && chmod +x /usr/bin/docker-credential-gcr
                      - docker-credential-gcr configure-docker --registries=europe-west1-docker.pkg.dev
                      - helm upgrade --install podtato-head ./ --namespace default
                    command: /bin/bash
                    run_if: passed
