apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: custom-argo-server-role
  namespace: argo
rules:
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflows-server-binding
  namespace: argo
subjects:
  - kind: ServiceAccount
    name: argo-workflows-server
    namespace: argo
roleRef:
  kind: Role
  name: custom-argo-server-role
  apiGroup: rbac.authorization.k8s.io
