apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-executor
  namespace: argo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-executor
  namespace: argo
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - patch
